package com.hutao.app.imageprivewproject.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hutao.app.imageprivewproject.model.ImageModel;
import com.hutao.app.imageprivewproject.model.Model;

import com.hutao.app.imageprivewproject.dao.ImageModelDao;
import com.hutao.app.imageprivewproject.dao.ModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageModelDaoConfig;
    private final DaoConfig modelDaoConfig;

    private final ImageModelDao imageModelDao;
    private final ModelDao modelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageModelDaoConfig = daoConfigMap.get(ImageModelDao.class).clone();
        imageModelDaoConfig.initIdentityScope(type);

        modelDaoConfig = daoConfigMap.get(ModelDao.class).clone();
        modelDaoConfig.initIdentityScope(type);

        imageModelDao = new ImageModelDao(imageModelDaoConfig, this);
        modelDao = new ModelDao(modelDaoConfig, this);

        registerDao(ImageModel.class, imageModelDao);
        registerDao(Model.class, modelDao);
    }
    
    public void clear() {
        imageModelDaoConfig.getIdentityScope().clear();
        modelDaoConfig.getIdentityScope().clear();
    }

    public ImageModelDao getImageModelDao() {
        return imageModelDao;
    }

    public ModelDao getModelDao() {
        return modelDao;
    }

}
